language: ruby
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - ruby-head

env:
  - "RAILS_VERSION=3.2.0"
  - "RAILS_VERSION=4.0.0"
  - "RAILS_VERSION=master"

matrix:
  allow_failures:
    - env: "RAILS_VERSION=master"
    - rvm: ruby-head
